### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by TerribleDev** [Janus-vistaprint/terraform-autoscale-ecs#1]
do you think it makes sense for our modules to take in tags so so people could tag their clusters with data? 
@jcharette do you know if this is actually a good idea/concern, and if so how could we let a user pass us in tag data? list of maps or something?

**Comment by jcharette** [comment]
Names of objects created already contain the Cluster name.  I don't feel tags are actually that useful in this case.

**Comment by TerribleDev** [comment]
👍
